import random


from Glass_Bridge import glass_bridge

def red_light():
    print(""" ***WELCOME TO THE FIRST GAME. THE OBJECTIVE OF THE GAME IS TO MAKE IT ACROSS THE ROOM IN 15 STEPS.***
                
        ***CHOOSE A STRATEGIC AMOUNT OF STEPS IN ORDER TO MOVE FORWARD DURING THE GREEN LIGHT, TAKE TOO MANY STEPS AND YOU RUN THE RISK OF GETTING SHOT***\n""")
    
    step_counter = 0                    # step counter to see if player gets to 15 steps and moves onto the next round
    app_running = True
    while app_running == True:
        
        robot = random.randint(9, 10)
        choice = int(input('Enter number of steps (1-10) you would like to take: \n'))
        
        if choice >= robot:                                     # If steps the player entered exceed the random number generated by robot, then kill the player
            print("""\nYOU MOVED ON A RED LIGHT AND GOT SHOT!\n 
            
        
______ _____  ___ ______ 
|  _  \  ___|/ _ \|  _  |
| | | | |__ / /_\ \ | | |
| | | |  __||  _  | | | |
| |/ /| |___| | | | |/ / 
|___/ \____/\_| |_/___/  

        @@@@@@@@@@@@@@@@@@
     @@@@@@@@@@@@@@@@@@@@@@@
   @@@@@@@@@@@@@@@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@     
 @@@@@@@@@@@@@@@/      \@@@/   @
@@@@@@@@@@@@@@@@\      @@  @___@
@@@@@@@@@@@@@ @@@@@@@@@@  | \@@@@@
@@@@@@@@@@@@@ @@@@@@@@@\__@_/@@@@@
 @@@@@@@@@@@@@@@/,/,/./'/_|.\*'\,\*
   @@@@@@@@@@@@@|  | | | | | | | |
                 \_|_|_|_|_|_|_|_|


            
            """)
            break
        elif choice <= robot:
            step_counter += choice
            print("You stopped on Red Light and survived!\n ")                             # takes action based on step count
            print("Take more steps in order to reach 15 total steps and survive the round\n")
            
            if step_counter >= 15:
                print("You survived the round!!\n ")
        else: 
            print("Please enter a valid number 1-10: ")
        

        if step_counter >= 15:
            next_game = input("\nPress y to play next game, press a to play again, or press q to quit: ")
            if next_game == 'y':
                glass_bridge()
            elif next_game == 'q':
                exit()

